### ISSUE TITLE
SCSS and CSS watches conflict

### ISSUE THREAD

**Issue by agopshi** [loewydesign/loewy-assets#4]
Looks like there are conflicts between the SCSS and CSS watches when multiple CSS files are generated by the SCSS compilation. The CSS watch ends up executing the `css` task multiple times (once per output CSS file), and that causes read/write issues.

To fix this, we should simplify the `sass.js` and `css.js` tasks into a single `styles.js` task which does the following:

1. Watch for updates to SCSS files. (Currently in `sass.js`.)
2. Compile the SCSS into CSS. (Currently in `sass.js`.)
3. Move the CSS files into the development CSS directory. (Currently in `sass.js`.)
4. Run `autoprefixer`. (Currently in `css.js`.)
5. Move the final CSS files into the release CSS directory. (Currently in `css.js`.)

**Comment by dan-ld** [comment]
@agopshi just need permission to update the npm package so I can commit the package.json version update in the develop branch and then merge with master.

**Comment by dan-ld** [comment]
@agopshi Thanks for the info. Scss and css tasks are now a single styles task. Update is in dev & master.

**Comment by agopshi** [comment]
@dan-ld Did you try this using a single stream instead of merging two streams?

**Comment by dan-ld** [comment]
@agop-ld I originally merged two streams but then updated it so that it currently is using a single stream.

--
Dan Morales
Solutions Developer
Office: (631) 249-2429 ext. 121
Hedgehog Development, LLC.<http://www.hhogdev.com/>
Products<http://www.hhogdev.com/products.aspx> |  Services<http://www.hhogdev.com/solutions.aspx> |  Twitter<https://twitter.com/hhogdev> |  Facebook<https://www.facebook.com/hhogdev> |  Linkedin<https://www.linkedin.com/company/hedgehog-development> |  Jobs<http://www.hhogdev.com/careers/jobopenings.aspx>

**Comment by agopshi** [comment]
@dan-ld Sweet, this is looking good. One last thing - make sure to return that gulp stream. Right now, it's just being assigned to a variable. Without returning the gulp stream (or calling the `done` callback), gulp has no way of knowing when the task finishes.

**Comment by dan-ld** [comment]
@agopshi Thanks! I've updated the task to return the gulp stream instead of calling the `done` callback.
